version: "3"

tasks:
  main:
    cmds:
      - echo "***Starting GODVP***"
      # - go clean -modcache
      - ./scripts/init.sh
      - go run . {{.CLI_ARGS}}

  server:
    cmds:
      - echo "***Starting Test/Server***"
      - go clean -modcache
      - go run /test/server.go {{.CLI_ARGS}}
  osquery:
    cmds:
      - echo "***Starting Test/Osquery***"
      - go clean -modcache
      - go run /test/osquery.go {{.CLI_ARGS}}
