version: "3"

tasks:
  main:
    cmds:
      - echo "***Starting GODVP***"
      - go run . {{.CLI_ARGS}}
  server:
    cmds:
      - echo "***Starting Test/Server***"
      - go run /test/server.go {{.CLI_ARGS}}
  osquery:
    cmds:
      - echo "***Starting Test/Osquery***"
      - go run /test/osquery.go {{.CLI_ARGS}}
