version: "3"

tasks:
  default:
    cmds:
      - touch .tsip
      - tailscale ip -4 > .tsip
      - cat .tsip
      - tailscale status --json | jq -r '.Self.UserID' > .devid
      - cat .devid
      - task osquery
      - cd current && sudo caddy file-server --domain=$(cat ../.tsip) --browse
  main:
    cmds:
      - echo "...Bootstrapping Go-DVP..."
      - ./scripts/init.sh
      - go run . {{.CLI_ARGS}}
  server:
    cmds:
      - echo "***Starting Test/Server***"
      - go run ./test/server.go {{.CLI_ARGS}}
  osquery:
    cmds:
      - echo "***Starting Test/Osquery***"
      - go run ./test/osquery.go {{.CLI_ARGS}}
  cache:
    cmds:
      - echo "...Cleaning Cache..."
      - go clean -modcache | echo "Cleaned Go Cache"
