version: "3"

tasks:
  main:
    cmds:
      - echo "***Starting GODVP***"
      - go run . {{.CLI_ARGS}}
  server:
    cmds:
      - echo "***Starting GODVP***"
      - go run /tailscale/server.go {{.CLI_ARGS}}
