version: "3"

tasks:
  default:
    cmds:
      - echo "*** Go-DVP - Node Information ***"
      - touch .tsip
      - tailscale ip -4 > .tsip
      - cat .tsip
      - tailscale status --json | jq -r '.Self.UserID' > .devid
      - cat .devid
  cli:
    cmds:
      - echo "*** Go-DVP CLI ***"
      - ./scripts/init.sh
      - go run . {{.CLI_ARGS}}
  server:
    cmds:
      - echo "*** Test/Server ***"
      - go run ./test/server.go {{.CLI_ARGS}}
  osquery:
    cmds:
      - echo "*** Test/Osquery ***"
      - go run ./test/osquery.go {{.CLI_ARGS}}
  cache:
    cmds:
      - echo "*** Cleaning Cache ***"
      - go clean -modcache | echo "Cleaned Go Cache"
  target:
    cmds:
      - echo "*** Bootstrapping Target ***"
      - ./scripts/init.sh
      - go run ./test/target.go {{.CLI_ARGS}}
  checker:
    cmds:
      - echo "*** Bootstrapping Checker ***"
      - ./scripts/init.sh
      - go run ./test/checker.go {{.CLI_ARGS}}
# target vs checker scripts
# target is what runs on the device
# checker can be the main script (CLI) we already have
# but for now just run a single script that checks the device